apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster1
spec:
  version: 7.14.0
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: localhost 
  nodeSets:
  - name: elasticsearch
    count: 3
    config:
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.elasticsearch.collection.enabled: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 4Gi
              limits:
                memory: 4Gi
            env:
            - name: ES_LOG_STYLE
              value: file
          - name: metricbeat
            image: docker.elastic.co/beats/metricbeat:7.14.0
            args: [
              "-c", "/etc/metricbeat.yml",
              "-e"
            ]
            env:
            - name: ELASTICSEARCH_USERNAME
              value: elastic # TODO use a dedicated monitoring user
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: cluster1-es-elastic-user
            - name: MONITOR_HOST
              value: cluster1-es-http
            - name: MONITOR_PORT
              value: "9200"
            - name: MONITOR_USERNAME
              value: elastic
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: cluster1-es-elastic-user
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            volumeMounts:
            - name: metricbeat-config
              mountPath: /etc/metricbeat.yml
              readOnly: true
              subPath: metricbeat.yml
            - name: monitoring-certs
              mountPath: /mnt/monitoring/tls.crt
              readOnly: true
              subPath: tls.crt
            - name: es-certs
              mountPath:  /mnt/elastic/tls.crt
              readOnly: true
              subPath: tls.crt
          - name: filebeat
            image: docker.elastic.co/beats/filebeat:7.14.0
            args: [
              "-c", "/etc/filebeat.yml",
              "-e"
            ]
            env:
            - name: MONITOR_HOST
              value: cluster1-es-http
            - name: MONITOR_PORT
              value: "9200"
            - name: MONITOR_USERNAME
              value: elastic
            - name: MONITOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: cluster1-es-elastic-user
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: monitoring-certs
              mountPath: /mnt/monitoring/tls.crt
              readOnly: true
              subPath: tls.crt
            - name: elasticsearch-logs
              mountPath: /usr/share/elasticsearch/logs
        volumes:
        - name: metricbeat-config
          configMap:
            name: configmap-metricbeat
        - name: monitoring-certs
          secret:
            secretName: cluster1-es-http-certs-public
        - name: es-certs
          secret:
            secretName: cluster1-es-http-certs-public
        - name: filebeat-config
          configMap:
            name: configmap-filebeat
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6Gi
            storageClassName: standard
